remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Einundzwanzig Community Plugins
description: Bitcoin-related Plugins for Elgato Stream Decks.
show_downloads: false
